all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    webservers:
      hosts:
        web1:
          ansible_host: 192.168.99.98
    dbservers:
      hosts:
        db1:
          ansible_host: 192.168.99.97

